### ISSUE TITLE
Feature request: Optional parameters

### ISSUE THREAD

**Issue by yig** [eliemichel/WebGPU-Cpp#5]
This is a feature request to have the C++ API generate methods with optional parameters like the C API. For example, `wgpuTextureCreateView()` has the `WGPUTextureViewDescriptor` marked as `WGPU_NULLABLE`. The chosen defaults for a null `WGPUTextureViewDescriptor` are quite desirable ([according to the specification](https://www.w3.org/TR/webgpu/#dom-gputexture-createview)). Notably, they are different than a zero-initialized `WGPUTextureViewDescriptor` struct. The C++ API requires one to pass a `WGPUTextureViewDescriptor` which is much less convenient.

**Comment by eliemichel** [comment]
Not intensively tested yet, but 9741270 introduces this feature!
