### ISSUE TITLE
Setup link to file doesnt work

### ISSUE THREAD

**Issue by TJHeuvel** [eliemichel/WebGPU-Cpp#6]
https://github.com/eliemichel/WebGPU-Cpp#setup

> Copy the file [webgpu.hpp](https://github.com/eliemichel/WebGPU-Cpp/blob/main/webgpu.hpp) file to your C++17 project.

This appears as a link, but that main webgpu.hpp cannot be found. Im unsure how you'd want to link this with them being split between dawn and native.

**Comment by eliemichel** [comment]
Thanks for spotting this!
